import Head from "next/head";
import Image from "next/image";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import Calendar from "../components/Calendar";
import Radiogroup from "../components/Radiogroup";

import dayjs from "dayjs";
import Plans from "../components/Plans";
import ContentSection from "../components/ContentSection";

export default function Home({ res, meetings, services }) {
  const jsonMeetings = meetings.map(
    ([id, startDatetime, endDatetime, status, name]) => ({
      id: Number(id),
      startDatetime,
      endDatetime,
      status,
      name,
    })
  );
  //   const jsonServices = services.map(
  //     ([id, title, description, minutes, price]) => ({
  //       id: Number(id),
  //       title,
  //       description,
  //       minutes: Number(minutes),
  //       price: Number(price)
  //     })
  //   ).slice(1)
  // console.log(jsonServices,'jsonServicesjsonServices');
  // startDatetime: dayjs(startDatetime).format(`YYYY-DD-MMTHH:mm`),
  // endDatetime: dayjs(endDatetime).format(`YYYY-DD-MMTHH:mm`),
  // console.log(jsonMeetings, "jsonMeetings");
  return (
    <>
      <Head>
        <title>Массажный салон Юрия Шпакова</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Hero meetings={jsonMeetings} />
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const req = await fetch("https://schpakov.com/api/sheets");
  const res = await req.json();

  const reqMeet = await fetch("https://schpakov.com/api/meetings");
  const resMeet = await reqMeet.json();

  const reqServices = await fetch("https://schpakov.com/api/services");
  const resServices = await reqServices.json();

  return {
    props: {
      res,
      meetings: resMeet.data,
      // services: resServices.data
    },
  };
}
